site_name: "alterNERDtive VA profiles"
site_url: https://alterNERDtive.github.io/VoiceAttack-profiles
repo_url: https://github.com/alterNERDtive/VoiceAttack-profiles
edit_uri: "edit/devel/docs/"
site_description: "alterNERDtive VoiceAttack profiles for Elite: Dangerous"
site_author: "alterNERDtive"
remote_name: "ssh-origin"

theme:
    name: readthedocs
    prev_next_buttons_location: both

plugins:
    - search
    - roamlinks
    # - mkpdfs:
    #     author: 'alterNERDtive'
    #     output_path: 'pdf/Profiles Documentation.pdf'

markdown_extensions:
    - toc:
        permalink: True
    - sane_lists

nav:
    - 'Home': 'index.md'
    - 'Install':
        - 'requirements.md'
        - 'installing.md'
        - 'upgrading.md'
    - 'Configure':
        - 'configuration/general.md'
        - 'configuration/EliteAttack.md'
        - 'configuration/RatAttack.md'
        - 'configuration/SpanshAttack.md'
        - 'configuration/StreamAttack.md'
    - 'Use':
        - 'general.md'
        - 'EliteAttack.md'
        - 'RatAttack.md'
        - 'SpanshAttack.md'
        - 'StreamAttack.md'
    - 'Issues':
        #- 'VoiceAttack Tips': 'VoiceAttack.md'
        - 'troubleshooting.md'
        - '⎋ Changelog': 'https://github.com/alterNERDtive/VoiceAttack-profiles/blob/release/CHANGELOG.md'
        - '⎋ Report a Bug': 'https://github.com/alterNERDtive/VoiceAttack-profiles/issues/'
    - 'Watch in Action':
        - '⎋ Twitch': 'https://twitch.tv/alterNERDtive'
        - '⎋ Youtube': 'https://www.youtube.com/channel/UC3XNZA7xWed1zM1AWOOdmog'
